### ISSUE TITLE
Approximately 90% of the `self.` in the code can and should be removed.

### ISSUE THREAD

**Issue by dasdom** [kn-neeraj/CGFLoatingUIKit#1]
Nearly all 'self.' are code noise and should be avoided, in my opinion.

**Comment by kn-neeraj** [comment]
Hi dasdom I totally get that the reason I dont let go of self if that in objective C if someone doesnt used a self for property then it was really confusing whether its a property of an instance variable.I have carried over that practice but surely this is swift I can let go of it.

**Comment by kn-neeraj** [comment]
Also Apple memory management guide says "Swift requires you to write self.someProperty or self.someMethod (rather than just someProperty or someMethod) whenever you refer to a member of self within a closure. This helps you remember that it’s possible to capture self by accident."
- I have seen lot newbie programmers doing this mistakes so I always tell them to go for self.someproperty to make program clearer for other and themselves.

**Comment by dasdom** [comment]
The compiler (even in the current buggy stage) is capable to figure that out and warn you. I'm going with Ray Wenderlich: https://github.com/raywenderlich/swift-style-guide#use-of-self

**Comment by kn-neeraj** [comment]
hmm i think i missed that. thanks for pointing it out.
